on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: dotnet build FastEndpoints.MediatR --configuration Release
    - name: Set VERSION variable from tag
      run: echo "VERSION=$(echo "${{ github.ref_name }}" | sed -E 's/v([0-9]+\.[0-9]+\.[0-9]+).*/\1/')" >> $GITHUB_ENV
    - name: Pack
      run: dotnet pack FastEndpoints.MediatR --configuration Release /p:Version=${VERSION} --output .
    - name: Push
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: dotnet nuget push MediatR.Enpoints.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key $TOKEN
